version: '3.7'
services:
    nginx:
        build: ./images/nginx
        container_name: nginxcontainer
        ports:
            - 80:80
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www/html
        links:
            - "php"

    php:
        build: ./images/php
        container_name: phpcontainer
        ports:
            - 9000:9000
        volumes:
           - ./www:/var/www/html
        environment:
            PHP_IDE_CONFIG: "serverName=PhpServerBase"